---
default_stages: [pre-commit]

repos:
  - repo: https://github.com/NixOS/nixfmt
    rev: 3245f221e4d9ab7e12ebe31fd193cb7a8c4b14f9  # frozen: v1.3.1
    hooks:
      - id: nixfmt-nix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 77039ccbba72c8aede339c5f8ae29b42aced0a2e  # frozen: v0.15.18
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: 7b04f660f4ee4f048d18fd341887cf28dfbedfe2  # frozen: v1.46.3
    hooks:
      - id: typos
        args: ["--force-exclude"]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 05c1426671b9237fb5e1444dd63aa5731bec0dfb  # frozen: v3.13.1-1
    hooks:
      - id: shfmt
        args: ["-w", "-s", "-i", "2"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d  # frozen: v0.11.0
    hooks:
      - id: shellcheck
        exclude: \.zsh$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda  # frozen: v0.22.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 63b8dbce992ca0fa201239acde684c053bf05fd1  # frozen: v1.1.5
    hooks:
      - id: tombi-format
      - id: tombi-lint

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["--strict", "-c=.yamllint.yaml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: no-commit-to-branch

  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: 286da5488db79f4cf5261e14a3c8976d89b5aa70  # frozen: v4.16.3
  #   hooks:
  #     - id: commitizen
  #     - id: commitizen-branch
  #       stages:
  #         - pre-push
