name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - flake.nix
      - flake.lock
      - home-modules/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/test.yaml
      - flake.nix
      - flake.lock
      - home-modules/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  user-repo:
    name: Test config-repository-based setup
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
    uses: ut-issl/issl-ubuntu-environment-setup/.github/workflows/test-environment.yaml@e029e761492db16b2c36a9f75955638a472d4dbb # v0.4.2
    with:
      setup-mode: repository-based
      os: ${{ matrix.os }}
      common-repository: ut-issl/issl-ubuntu-environment-setup
      common-ref: e029e761492db16b2c36a9f75955638a472d4dbb # v0.4.2
      user-repository: ${{ github.repository }}
      user-ref: ${{ github.sha }}
      override-issl-input: false
      timeout-minutes: 10
